[package]
name = "example"
version = "0.1.0"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true

[dependencies]
axum = { version = "0.8.9", features = ["http2"] }
beeline = { path = "../beeline", features = ["h1", "h2"] }
tokio = { version = "1.52", features = ["full"] }
httlib-huffman = "0.3.4"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tower = "0.5"
tower-http = { version = "0.7", features = ["fs", "trace", "set-status"] }
libc = "0.2.189"
anyhow = "1.0.104"
as-bytes = "0.2.0"
xbpf = { git = "https://github.com/lbrndnr/ebpf.git", branch = "map" }

[build-dependencies]
xbpf = { git = "https://github.com/lbrndnr/ebpf.git", branch = "map", features = ["build"] }
beeline-include = { path = "../beeline-include" }
