// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(renamed_and_removed_lints)]
#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::upper_case_acronyms)]
#[allow(clippy::zero_repeat_side_effects)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports, clippy::wildcard_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;
    use libbpf_rs::AsRawLibbpf as _;
    use libbpf_rs::MapCore as _;
    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder
            .name("prog_bpf")
            .map("upgraded_conns", false)
            .map("matches", false)
            .map("sock_map", false)
            .map("prog_bpf.bss", true)
            .map("prog_bpf.rodata", true)
            .prog("msg_verdict")
            .prog("monitor_sockets")
            .prog("get_num_upgraded_conns");
        builder.build()
    }
    pub struct OpenProgMaps<'obj> {
        pub upgraded_conns: libbpf_rs::OpenMapMut<'obj>,
        pub matches: libbpf_rs::OpenMapMut<'obj>,
        pub sock_map: libbpf_rs::OpenMapMut<'obj>,
        pub bss: libbpf_rs::OpenMapMut<'obj>,
        pub bss_data: Option<&'obj mut types::bss>,
        pub rodata: libbpf_rs::OpenMapMut<'obj>,
        pub rodata_data: Option<&'obj mut types::rodata>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenProgMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::OpenObject,
        ) -> libbpf_rs::Result<Self> {
            let mut upgraded_conns = None;
            let mut matches = None;
            let mut sock_map = None;
            let mut bss = None;
            let mut rodata = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "upgraded_conns" => upgraded_conns = Some(map),
                    "matches" => matches = Some(map),
                    "sock_map" => sock_map = Some(map),
                    "prog_bpf.bss" => bss = Some(map),
                    "prog_bpf.rodata" => rodata = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                upgraded_conns: upgraded_conns.expect("map `upgraded_conns` not present"),
                matches: matches.expect("map `matches` not present"),
                sock_map: sock_map.expect("map `sock_map` not present"),
                bss: bss.expect("map `bss` not present"),
                bss_data: unsafe {
                    config
                        .map_mmap_ptr(3)
                        .expect("BPF map `bss` does not have mmap pointer")
                        .cast::<types::bss>()
                        .as_mut()
                },
                rodata: rodata.expect("map `rodata` not present"),
                rodata_data: unsafe {
                    config
                        .map_mmap_ptr(4)
                        .expect("BPF map `rodata` does not have mmap pointer")
                        .cast::<types::rodata>()
                        .as_mut()
                },
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct ProgMaps<'obj> {
        pub upgraded_conns: libbpf_rs::MapMut<'obj>,
        pub matches: libbpf_rs::MapMut<'obj>,
        pub sock_map: libbpf_rs::MapMut<'obj>,
        pub bss: libbpf_rs::MapMut<'obj>,
        pub bss_data: Option<&'obj mut types::bss>,
        pub rodata: libbpf_rs::MapMut<'obj>,
        pub rodata_data: Option<&'obj types::rodata>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> ProgMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::Object,
        ) -> libbpf_rs::Result<Self> {
            let mut upgraded_conns = None;
            let mut matches = None;
            let mut sock_map = None;
            let mut bss = None;
            let mut rodata = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::Object, &'obj mut libbpf_rs::Object>(object)
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "upgraded_conns" => upgraded_conns = Some(map),
                    "matches" => matches = Some(map),
                    "sock_map" => sock_map = Some(map),
                    "prog_bpf.bss" => bss = Some(map),
                    "prog_bpf.rodata" => rodata = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                upgraded_conns: upgraded_conns.expect("map `upgraded_conns` not present"),
                matches: matches.expect("map `matches` not present"),
                sock_map: sock_map.expect("map `sock_map` not present"),
                bss: bss.expect("map `bss` not present"),
                bss_data: unsafe {
                    config
                        .map_mmap_ptr(3)
                        .expect("BPF map `bss` does not have mmap pointer")
                        .cast::<types::bss>()
                        .as_mut()
                },
                rodata: rodata.expect("map `rodata` not present"),
                rodata_data: unsafe {
                    config
                        .map_mmap_ptr(4)
                        .expect("BPF map `rodata` does not have mmap pointer")
                        .cast::<types::rodata>()
                        .as_ref()
                },
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct OpenProgProgs<'obj> {
        pub msg_verdict: libbpf_rs::OpenProgramMut<'obj>,
        pub monitor_sockets: libbpf_rs::OpenProgramMut<'obj>,
        pub get_num_upgraded_conns: libbpf_rs::OpenProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenProgProgs<'obj> {
        unsafe fn new(object: &mut libbpf_rs::OpenObject) -> libbpf_rs::Result<Self> {
            let mut msg_verdict = None;
            let mut monitor_sockets = None;
            let mut get_num_upgraded_conns = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            for prog in object.progs_mut() {
                let name = prog.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "prog has invalid name",
                    ))
                })?;
                match name {
                    "msg_verdict" => msg_verdict = Some(prog),
                    "monitor_sockets" => monitor_sockets = Some(prog),
                    "get_num_upgraded_conns" => get_num_upgraded_conns = Some(prog),
                    _ => panic!("encountered unexpected prog: `{name}`"),
                }
            }

            let slf = Self {
                msg_verdict: msg_verdict.expect("prog `msg_verdict` not present"),
                monitor_sockets: monitor_sockets.expect("prog `monitor_sockets` not present"),
                get_num_upgraded_conns: get_num_upgraded_conns
                    .expect("prog `get_num_upgraded_conns` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct ProgProgs<'obj> {
        pub msg_verdict: libbpf_rs::ProgramMut<'obj>,
        pub monitor_sockets: libbpf_rs::ProgramMut<'obj>,
        pub get_num_upgraded_conns: libbpf_rs::ProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> ProgProgs<'obj> {
        #[allow(unused_variables)]
        fn new(open_progs: OpenProgProgs<'obj>) -> Self {
            Self {
                msg_verdict: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs.msg_verdict.as_libbpf_object().as_mut(),
                    )
                },
                monitor_sockets: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs.monitor_sockets.as_libbpf_object().as_mut(),
                    )
                },
                get_num_upgraded_conns: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs
                            .get_num_upgraded_conns
                            .as_libbpf_object()
                            .as_mut(),
                    )
                },
                _phantom: std::marker::PhantomData,
            }
        }
    }
    struct OwnedRef<'obj, O> {
        object: Option<&'obj mut std::mem::MaybeUninit<O>>,
    }

    impl<'obj, O> OwnedRef<'obj, O> {
        /// # Safety
        /// The object has to be initialized.
        unsafe fn new(object: &'obj mut std::mem::MaybeUninit<O>) -> Self {
            Self {
                object: Some(object),
            }
        }

        fn as_ref(&self) -> &O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_ref().unwrap().assume_init_ref() }
        }

        fn as_mut(&mut self) -> &mut O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_mut().unwrap().assume_init_mut() }
        }

        fn take(mut self) -> &'obj mut std::mem::MaybeUninit<O> {
            self.object.take().unwrap()
        }
    }

    impl<O> Drop for OwnedRef<'_, O> {
        fn drop(&mut self) {
            if let Some(object) = &mut self.object {
                unsafe { object.assume_init_drop() }
            }
        }
    }

    #[derive(Default)]
    pub struct ProgSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'obj> ProgSkelBuilder {
        fn open_opts_impl(
            self,
            open_opts: *const libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenProgSkel<'obj>> {
            let skel_config = build_skel_config()?;
            let skel_ptr = skel_config.as_libbpf_object();

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_ptr.as_ptr(), open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            // SAFETY: `skel_ptr` points to a valid object after the
            //         open call.
            let obj_ptr = unsafe { *skel_ptr.as_ref().obj };
            // SANITY: `bpf_object__open_skeleton` should have
            //         allocated the object.
            let obj_ptr = std::ptr::NonNull::new(obj_ptr).unwrap();
            // SAFETY: `obj_ptr` points to an opened object after
            //         skeleton open.
            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(obj_ptr) };
            let _obj = object.write(obj);
            // SAFETY: We just wrote initialized data to `object`.
            let mut obj_ref = unsafe { OwnedRef::new(object) };

            #[allow(unused_mut)]
            let mut skel = OpenProgSkel {
                maps: unsafe { OpenProgMaps::new(&skel_config, obj_ref.as_mut())? },
                progs: unsafe { OpenProgProgs::new(obj_ref.as_mut())? },
                obj: obj_ref,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }
    }

    impl<'obj> SkelBuilder<'obj> for ProgSkelBuilder {
        type Output = OpenProgSkel<'obj>;
        fn open(
            self,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenProgSkel<'obj>> {
            self.open_opts_impl(std::ptr::null(), object)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenProgSkel<'obj>> {
            self.open_opts_impl(&open_opts, object)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    #[derive(Debug, Clone)]
    #[repr(C)]
    pub struct StructOps {}

    impl StructOps {}
    pub mod types {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct sock_key {
            pub local: addr_key,
            pub remote: addr_key,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct addr_key {
            pub ip4: u32,
            pub port: u32,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_1 {
            pub r#type: *mut [i32; 1],
            pub max_entries: *mut [i32; 16384],
            pub key: *mut sock_key,
            pub value: *mut i32,
        }
        impl Default for __anon_1 {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    max_entries: std::ptr::null_mut(),
                    key: std::ptr::null_mut(),
                    value: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_2 {
            pub r#type: *mut [i32; 1],
            pub max_entries: *mut [i32; 32],
            pub key: *mut u32,
            pub value: *mut [i8; 128],
        }
        impl Default for __anon_2 {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    max_entries: std::ptr::null_mut(),
                    key: std::ptr::null_mut(),
                    value: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_3 {
            pub r#type: *mut [i32; 18],
            pub max_entries: *mut [i32; 16384],
            pub key: *mut sock_key,
            pub value: *mut i32,
        }
        impl Default for __anon_3 {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    max_entries: std::ptr::null_mut(),
                    key: std::ptr::null_mut(),
                    value: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct sk_msg_md {
            pub __anon_sk_msg_md_1: __anon_sk_msg_md_1,
            pub __anon_sk_msg_md_2: __anon_sk_msg_md_2,
            pub family: u32,
            pub remote_ip4: u32,
            pub local_ip4: u32,
            pub remote_ip6: [u32; 4],
            pub local_ip6: [u32; 4],
            pub remote_port: u32,
            pub local_port: u32,
            pub size: u32,
            pub __anon_sk_msg_md_3: __anon_sk_msg_md_3,
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_sk_msg_md_1 {
            pub data: *mut std::ffi::c_void,
        }
        impl std::fmt::Debug for __anon_sk_msg_md_1 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_sk_msg_md_1 {
            fn default() -> Self {
                Self {
                    data: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_sk_msg_md_2 {
            pub data_end: *mut std::ffi::c_void,
        }
        impl std::fmt::Debug for __anon_sk_msg_md_2 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_sk_msg_md_2 {
            fn default() -> Self {
                Self {
                    data_end: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_sk_msg_md_3 {
            pub sk: *mut bpf_sock,
        }
        impl std::fmt::Debug for __anon_sk_msg_md_3 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_sk_msg_md_3 {
            fn default() -> Self {
                Self {
                    sk: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct bpf_sock {
            pub bound_dev_if: u32,
            pub family: u32,
            pub r#type: u32,
            pub protocol: u32,
            pub mark: u32,
            pub priority: u32,
            pub src_ip4: u32,
            pub src_ip6: [u32; 4],
            pub src_port: u32,
            pub dst_port: u16,
            pub dst_ip4: u32,
            pub dst_ip6: [u32; 4],
            pub state: u32,
            pub rx_queue_mapping: i32,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct hdr_str {
            pub len: u32,
            pub __pad_4: [u8; 4],
            pub ptr: *mut u8,
        }
        impl Default for hdr_str {
            fn default() -> Self {
                Self {
                    len: u32::default(),
                    __pad_4: [u8::default(); 4],
                    ptr: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct bpf_iter_num {
            pub __opaque: [u64; 1],
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct bpf_sock_ops {
            pub op: u32,
            pub __anon_bpf_sock_ops_1: __anon_bpf_sock_ops_1,
            pub family: u32,
            pub remote_ip4: u32,
            pub local_ip4: u32,
            pub remote_ip6: [u32; 4],
            pub local_ip6: [u32; 4],
            pub remote_port: u32,
            pub local_port: u32,
            pub is_fullsock: u32,
            pub snd_cwnd: u32,
            pub srtt_us: u32,
            pub bpf_sock_ops_cb_flags: u32,
            pub state: u32,
            pub rtt_min: u32,
            pub snd_ssthresh: u32,
            pub rcv_nxt: u32,
            pub snd_nxt: u32,
            pub snd_una: u32,
            pub mss_cache: u32,
            pub ecn_flags: u32,
            pub rate_delivered: u32,
            pub rate_interval_us: u32,
            pub packets_out: u32,
            pub retrans_out: u32,
            pub total_retrans: u32,
            pub segs_in: u32,
            pub data_segs_in: u32,
            pub segs_out: u32,
            pub data_segs_out: u32,
            pub lost_out: u32,
            pub sacked_out: u32,
            pub sk_txhash: u32,
            pub bytes_received: u64,
            pub bytes_acked: u64,
            pub __anon_sk_msg_md_3: __anon_sk_msg_md_3,
            pub __anon_bpf_sock_ops_2: __anon_bpf_sock_ops_2,
            pub __anon_bpf_sock_ops_3: __anon_bpf_sock_ops_3,
            pub skb_len: u32,
            pub skb_tcp_flags: u32,
            pub skb_hwtstamp: u64,
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_bpf_sock_ops_1 {
            pub args: [u32; 4],
            pub reply: u32,
            pub replylong: [u32; 4],
        }
        impl std::fmt::Debug for __anon_bpf_sock_ops_1 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_bpf_sock_ops_1 {
            fn default() -> Self {
                Self {
                    args: [u32::default(); 4],
                }
            }
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_bpf_sock_ops_2 {
            pub skb_data: *mut std::ffi::c_void,
        }
        impl std::fmt::Debug for __anon_bpf_sock_ops_2 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_bpf_sock_ops_2 {
            fn default() -> Self {
                Self {
                    skb_data: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_bpf_sock_ops_3 {
            pub skb_data_end: *mut std::ffi::c_void,
        }
        impl std::fmt::Debug for __anon_bpf_sock_ops_3 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_bpf_sock_ops_3 {
            fn default() -> Self {
                Self {
                    skb_data_end: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct license {
            pub LICENSE: [i8; 4],
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct bss {
            pub num_upgraded_conns: u32,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct rodata {
            pub ip4: u32,
            pub port: u32,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct maps {
            pub upgraded_conns: __anon_1,
            pub matches: __anon_2,
            pub sock_map: __anon_3,
        }
    }
    pub struct OpenProgSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::OpenObject>,
        pub maps: OpenProgMaps<'obj>,
        pub progs: OpenProgProgs<'obj>,
        pub struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
    }

    impl<'obj> OpenSkel<'obj> for OpenProgSkel<'obj> {
        type Output = ProgSkel<'obj>;
        fn load(self) -> libbpf_rs::Result<ProgSkel<'obj>> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();

            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj_ref = self.obj.take();
            let open_obj = std::mem::replace(obj_ref, std::mem::MaybeUninit::uninit());
            // SAFETY: `open_obj` is guaranteed to be properly
            //         initialized as it came from an `OwnedRef`.
            let obj_ptr = unsafe { open_obj.assume_init().take_ptr() };
            // SAFETY: `obj_ptr` points to a loaded object after
            //         skeleton load.
            let obj = unsafe { libbpf_rs::Object::from_ptr(obj_ptr) };
            // SAFETY: `OpenObject` and `Object` are guaranteed to
            //         have the same memory layout.
            let obj_ref = unsafe {
                std::mem::transmute::<
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::Object>,
                >(obj_ref)
            };
            let _obj = obj_ref.write(obj);
            // SAFETY: We just wrote initialized data to `obj_ref`.
            let mut obj_ref = unsafe { OwnedRef::new(obj_ref) };

            Ok(ProgSkel {
                maps: unsafe { ProgMaps::new(&self.skel_config, obj_ref.as_mut())? },
                progs: ProgProgs::new(self.progs),
                obj: obj_ref,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: ProgLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            self.obj.as_ref()
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            self.obj.as_mut()
        }
    }
    #[derive(Default)]
    pub struct ProgLinks {
        pub msg_verdict: Option<libbpf_rs::Link>,
        pub monitor_sockets: Option<libbpf_rs::Link>,
        pub get_num_upgraded_conns: Option<libbpf_rs::Link>,
    }
    pub struct ProgSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::Object>,
        pub maps: ProgMaps<'obj>,
        pub progs: ProgProgs<'obj>,
        struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
        pub links: ProgLinks,
    }

    unsafe impl Send for ProgSkel<'_> {}
    unsafe impl Sync for ProgSkel<'_> {}

    impl<'obj> Skel<'obj> for ProgSkel<'obj> {
        fn object(&self) -> &libbpf_rs::Object {
            self.obj.as_ref()
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            self.obj.as_mut()
        }
        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = ProgLinks {
                msg_verdict: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
                monitor_sockets: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(1)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
                get_num_upgraded_conns: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(2)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl ProgSkel<'_> {
        pub fn struct_ops_raw(&self) -> *const StructOps {
            &self.struct_ops
        }

        pub fn struct_ops(&self) -> &StructOps {
            &self.struct_ops
        }
    }
    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 248, 52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 64, 0, 16, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97,
        98, 0, 46, 116, 101, 120, 116, 0, 115, 107, 95, 109, 115, 103, 0, 115, 111, 99, 107, 111,
        112, 115, 0, 115, 121, 115, 99, 97, 108, 108, 0, 108, 105, 99, 101, 110, 115, 101, 0, 46,
        98, 115, 115, 0, 46, 114, 111, 100, 97, 116, 97, 0, 46, 109, 97, 112, 115, 0, 112, 114,
        111, 103, 46, 98, 112, 102, 46, 99, 0, 76, 66, 66, 51, 95, 51, 0, 109, 115, 103, 95, 118,
        101, 114, 100, 105, 99, 116, 46, 95, 95, 95, 102, 109, 116, 0, 76, 66, 66, 51, 95, 49, 54,
        0, 76, 66, 66, 51, 95, 54, 0, 109, 115, 103, 95, 118, 101, 114, 100, 105, 99, 116, 46, 95,
        95, 95, 95, 102, 109, 116, 0, 76, 66, 66, 51, 95, 49, 55, 0, 76, 66, 66, 51, 95, 57, 0, 76,
        66, 66, 51, 95, 56, 0, 76, 66, 66, 51, 95, 49, 48, 0, 76, 66, 66, 51, 95, 49, 52, 0, 76,
        66, 66, 51, 95, 49, 51, 0, 76, 66, 66, 51, 95, 49, 53, 0, 76, 66, 66, 52, 95, 50, 0, 76,
        66, 66, 52, 95, 56, 0, 109, 111, 110, 105, 116, 111, 114, 95, 115, 111, 99, 107, 101, 116,
        115, 46, 95, 95, 95, 102, 109, 116, 0, 76, 66, 66, 52, 95, 54, 0, 109, 111, 110, 105, 116,
        111, 114, 95, 115, 111, 99, 107, 101, 116, 115, 46, 95, 95, 95, 102, 109, 116, 46, 49, 0,
        76, 66, 66, 52, 95, 55, 0, 109, 111, 110, 105, 116, 111, 114, 95, 115, 111, 99, 107, 101,
        116, 115, 46, 95, 95, 95, 102, 109, 116, 46, 50, 0, 101, 120, 116, 114, 97, 99, 116, 95,
        109, 97, 116, 99, 104, 0, 112, 97, 114, 115, 101, 95, 104, 49, 0, 112, 97, 114, 115, 101,
        95, 104, 50, 0, 109, 115, 103, 95, 118, 101, 114, 100, 105, 99, 116, 0, 105, 112, 52, 0,
        112, 111, 114, 116, 0, 117, 112, 103, 114, 97, 100, 101, 100, 95, 99, 111, 110, 110, 115,
        0, 98, 112, 102, 95, 105, 116, 101, 114, 95, 110, 117, 109, 95, 110, 101, 119, 0, 98, 112,
        102, 95, 105, 116, 101, 114, 95, 110, 117, 109, 95, 110, 101, 120, 116, 0, 98, 112, 102,
        95, 105, 116, 101, 114, 95, 110, 117, 109, 95, 100, 101, 115, 116, 114, 111, 121, 0, 109,
        97, 116, 99, 104, 101, 115, 0, 110, 117, 109, 95, 117, 112, 103, 114, 97, 100, 101, 100,
        95, 99, 111, 110, 110, 115, 0, 109, 111, 110, 105, 116, 111, 114, 95, 115, 111, 99, 107,
        101, 116, 115, 0, 115, 111, 99, 107, 95, 109, 97, 112, 0, 103, 101, 116, 95, 110, 117, 109,
        95, 117, 112, 103, 114, 97, 100, 101, 100, 95, 99, 111, 110, 110, 115, 0, 76, 73, 67, 69,
        78, 83, 69, 0, 46, 114, 101, 108, 115, 107, 95, 109, 115, 103, 0, 46, 114, 101, 108, 115,
        111, 99, 107, 111, 112, 115, 0, 46, 114, 101, 108, 115, 121, 115, 99, 97, 108, 108, 0, 46,
        66, 84, 70, 0, 46, 66, 84, 70, 46, 101, 120, 116, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 73, 0, 0, 0, 4, 0, 241, 255, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 84, 0,
        0, 0, 0, 0, 4, 0, 184, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 91, 0, 0, 0, 1, 0, 9,
        0, 8, 0, 0, 0, 0, 0, 0, 0, 60, 0, 0, 0, 0, 0, 0, 0, 110, 0, 0, 0, 0, 0, 4, 0, 16, 4, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 118, 0, 0, 0, 0, 0, 4, 0, 184, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 125, 0, 0, 0, 1, 0, 9, 0, 68, 0, 0, 0, 0, 0, 0, 0, 38, 0, 0, 0, 0, 0,
        0, 0, 145, 0, 0, 0, 0, 0, 4, 0, 152, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 153, 0,
        0, 0, 0, 0, 4, 0, 64, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 160, 0, 0, 0, 0, 0, 4,
        0, 40, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 167, 0, 0, 0, 0, 0, 4, 0, 96, 2, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 175, 0, 0, 0, 0, 0, 4, 0, 192, 3, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 183, 0, 0, 0, 0, 0, 4, 0, 216, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 191, 0, 0, 0, 0, 0, 4, 0, 232, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 3, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 199, 0, 0, 0, 0, 0, 5, 0,
        40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 206, 0, 0, 0, 0, 0, 5, 0, 120, 2, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 213, 0, 0, 0, 1, 0, 9, 0, 106, 0, 0, 0, 0, 0, 0, 0, 38, 0,
        0, 0, 0, 0, 0, 0, 236, 0, 0, 0, 0, 0, 5, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        243, 0, 0, 0, 1, 0, 9, 0, 144, 0, 0, 0, 0, 0, 0, 0, 47, 0, 0, 0, 0, 0, 0, 0, 12, 1, 0, 0,
        0, 0, 5, 0, 104, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 1, 0, 0, 1, 0, 9, 0, 191,
        0, 0, 0, 0, 0, 0, 0, 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 44, 1, 0, 0, 18, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 136, 0, 0, 0, 0, 0, 0, 0, 58, 1,
        0, 0, 18, 0, 3, 0, 136, 0, 0, 0, 0, 0, 0, 0, 104, 0, 0, 0, 0, 0, 0, 0, 67, 1, 0, 0, 18, 0,
        3, 0, 240, 0, 0, 0, 0, 0, 0, 0, 104, 0, 0, 0, 0, 0, 0, 0, 76, 1, 0, 0, 18, 0, 4, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 168, 4, 0, 0, 0, 0, 0, 0, 88, 1, 0, 0, 17, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 4, 0, 0, 0, 0, 0, 0, 0, 92, 1, 0, 0, 17, 0, 9, 0, 4, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0,
        0, 0, 0, 97, 1, 0, 0, 17, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 112,
        1, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 129, 1, 0, 0, 32, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 147, 1, 0, 0, 32, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 168, 1, 0, 0, 17, 0, 10, 0, 32, 0, 0, 0, 0, 0, 0, 0,
        32, 0, 0, 0, 0, 0, 0, 0, 176, 1, 0, 0, 17, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0,
        0, 0, 0, 195, 1, 0, 0, 18, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 136, 2, 0, 0, 0, 0, 0, 0, 211,
        1, 0, 0, 17, 0, 10, 0, 64, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 220, 1, 0, 0, 18,
        0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 243, 1, 0, 0, 17, 0, 7, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 115, 42, 247, 255, 0, 0, 0, 0, 123, 26, 248, 255,
        0, 0, 0, 0, 123, 58, 232, 255, 0, 0, 0, 0, 24, 4, 0, 0, 255, 255, 255, 255, 0, 0, 0, 0, 0,
        0, 0, 0, 99, 74, 228, 255, 0, 0, 0, 0, 123, 26, 248, 255, 0, 0, 0, 0, 115, 42, 247, 255, 0,
        0, 0, 0, 123, 58, 232, 255, 0, 0, 0, 0, 99, 74, 228, 255, 0, 0, 0, 0, 121, 161, 248, 255,
        0, 0, 0, 0, 97, 19, 68, 0, 0, 0, 0, 0, 183, 2, 0, 0, 0, 0, 0, 0, 183, 4, 0, 0, 0, 0, 0, 0,
        133, 0, 0, 0, 63, 0, 0, 0, 97, 160, 228, 255, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 123,
        26, 248, 255, 0, 0, 0, 0, 24, 2, 0, 0, 255, 255, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 99, 42,
        244, 255, 0, 0, 0, 0, 123, 26, 248, 255, 0, 0, 0, 0, 99, 42, 244, 255, 0, 0, 0, 0, 121,
        161, 248, 255, 0, 0, 0, 0, 97, 19, 68, 0, 0, 0, 0, 0, 183, 2, 0, 0, 0, 0, 0, 0, 183, 4, 0,
        0, 0, 0, 0, 0, 133, 0, 0, 0, 63, 0, 0, 0, 97, 160, 244, 255, 0, 0, 0, 0, 149, 0, 0, 0, 0,
        0, 0, 0, 123, 26, 248, 255, 0, 0, 0, 0, 24, 2, 0, 0, 255, 255, 255, 255, 0, 0, 0, 0, 0, 0,
        0, 0, 99, 42, 244, 255, 0, 0, 0, 0, 123, 26, 248, 255, 0, 0, 0, 0, 99, 42, 244, 255, 0, 0,
        0, 0, 121, 161, 248, 255, 0, 0, 0, 0, 97, 19, 68, 0, 0, 0, 0, 0, 183, 2, 0, 0, 0, 0, 0, 0,
        183, 4, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 63, 0, 0, 0, 97, 160, 244, 255, 0, 0, 0, 0, 149, 0,
        0, 0, 0, 0, 0, 0, 191, 22, 0, 0, 0, 0, 0, 0, 97, 97, 24, 0, 0, 0, 0, 0, 99, 26, 240, 255,
        0, 0, 0, 0, 183, 3, 0, 0, 0, 0, 0, 0, 191, 162, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 248, 255,
        255, 255, 97, 97, 64, 0, 0, 0, 0, 0, 99, 26, 244, 255, 0, 0, 0, 0, 97, 101, 20, 0, 0, 0, 0,
        0, 99, 90, 248, 255, 0, 0, 0, 0, 97, 100, 60, 0, 0, 0, 0, 0, 220, 4, 0, 0, 32, 0, 0, 0, 99,
        74, 252, 255, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 97, 0, 0, 0, 0,
        0, 0, 0, 93, 5, 6, 0, 0, 0, 0, 0, 24, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 97, 53,
        0, 0, 0, 0, 0, 0, 183, 3, 0, 0, 1, 0, 0, 0, 29, 84, 1, 0, 0, 0, 0, 0, 183, 3, 0, 0, 0, 0,
        0, 0, 97, 101, 68, 0, 0, 0, 0, 0, 123, 58, 120, 255, 0, 0, 0, 0, 123, 74, 112, 255, 0, 0,
        0, 0, 123, 42, 104, 255, 0, 0, 0, 0, 123, 26, 96, 255, 0, 0, 0, 0, 123, 90, 80, 255, 0, 0,
        0, 0, 191, 167, 0, 0, 0, 0, 0, 0, 7, 7, 0, 0, 240, 255, 255, 255, 123, 122, 88, 255, 0, 0,
        0, 0, 191, 163, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 80, 255, 255, 255, 24, 1, 0, 0, 8, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 60, 0, 0, 0, 183, 4, 0, 0, 48, 0, 0, 0, 133, 0, 0, 0,
        177, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 191, 114, 0, 0, 0, 0, 0, 0,
        133, 0, 0, 0, 1, 0, 0, 0, 21, 0, 86, 0, 0, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 133, 16, 0,
        0, 255, 255, 255, 255, 103, 0, 0, 0, 32, 0, 0, 0, 199, 0, 0, 0, 32, 0, 0, 0, 101, 0, 6, 0,
        255, 255, 255, 255, 121, 99, 0, 0, 0, 0, 0, 0, 24, 1, 0, 0, 68, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 183, 2, 0, 0, 38, 0, 0, 0, 133, 0, 0, 0, 6, 0, 0, 0, 5, 0, 92, 0, 0, 0, 0, 0, 183, 1,
        0, 0, 10, 0, 0, 0, 109, 1, 90, 0, 0, 0, 0, 0, 183, 8, 0, 0, 0, 0, 0, 0, 99, 138, 236, 255,
        0, 0, 0, 0, 191, 167, 0, 0, 0, 0, 0, 0, 7, 7, 0, 0, 224, 255, 255, 255, 183, 9, 0, 0, 32,
        0, 0, 0, 191, 113, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 0, 0, 0, 0, 183, 3, 0, 0, 32, 0, 0, 0,
        133, 16, 0, 0, 255, 255, 255, 255, 191, 113, 0, 0, 0, 0, 0, 0, 133, 16, 0, 0, 255, 255,
        255, 255, 21, 0, 3, 0, 0, 0, 0, 0, 97, 2, 0, 0, 0, 0, 0, 0, 99, 42, 236, 255, 0, 0, 0, 0,
        45, 41, 4, 0, 0, 0, 0, 0, 191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 224, 255, 255, 255, 133,
        16, 0, 0, 255, 255, 255, 255, 5, 0, 71, 0, 0, 0, 0, 0, 123, 138, 216, 255, 0, 0, 0, 0, 123,
        138, 208, 255, 0, 0, 0, 0, 87, 2, 0, 0, 255, 0, 0, 0, 191, 163, 0, 0, 0, 0, 0, 0, 7, 3, 0,
        0, 208, 255, 255, 255, 191, 97, 0, 0, 0, 0, 0, 0, 133, 16, 0, 0, 255, 255, 255, 255, 103,
        0, 0, 0, 32, 0, 0, 0, 119, 0, 0, 0, 32, 0, 0, 0, 85, 0, 34, 0, 0, 0, 0, 0, 97, 162, 208,
        255, 0, 0, 0, 0, 87, 2, 0, 0, 255, 255, 0, 0, 183, 1, 0, 0, 128, 0, 0, 0, 45, 33, 1, 0, 0,
        0, 0, 0, 183, 2, 0, 0, 128, 0, 0, 0, 123, 138, 200, 255, 0, 0, 0, 0, 123, 138, 192, 255, 0,
        0, 0, 0, 123, 138, 184, 255, 0, 0, 0, 0, 123, 138, 176, 255, 0, 0, 0, 0, 123, 138, 168,
        255, 0, 0, 0, 0, 123, 138, 160, 255, 0, 0, 0, 0, 123, 138, 152, 255, 0, 0, 0, 0, 123, 138,
        144, 255, 0, 0, 0, 0, 123, 138, 136, 255, 0, 0, 0, 0, 123, 138, 128, 255, 0, 0, 0, 0, 123,
        138, 120, 255, 0, 0, 0, 0, 123, 138, 112, 255, 0, 0, 0, 0, 123, 138, 104, 255, 0, 0, 0, 0,
        123, 138, 96, 255, 0, 0, 0, 0, 123, 138, 88, 255, 0, 0, 0, 0, 123, 138, 80, 255, 0, 0, 0,
        0, 121, 163, 216, 255, 0, 0, 0, 0, 191, 167, 0, 0, 0, 0, 0, 0, 7, 7, 0, 0, 80, 255, 255,
        255, 191, 113, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 113, 0, 0, 0, 191, 162, 0, 0, 0, 0, 0, 0, 7,
        2, 0, 0, 236, 255, 255, 255, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 191, 115, 0,
        0, 0, 0, 0, 0, 183, 4, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 2, 0, 0, 0, 5, 0, 5, 0, 0, 0, 0, 0,
        191, 162, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 236, 255, 255, 255, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 3, 0, 0, 0, 191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 224,
        255, 255, 255, 133, 16, 0, 0, 255, 255, 255, 255, 21, 0, 199, 255, 0, 0, 0, 0, 5, 0, 195,
        255, 0, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 133, 16, 0, 0, 255, 255, 255, 255, 183, 1, 0,
        0, 1, 0, 0, 0, 99, 26, 80, 255, 0, 0, 0, 0, 191, 162, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 240,
        255, 255, 255, 191, 163, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 80, 255, 255, 255, 24, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 4, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 2, 0, 0, 0, 24, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 97, 18, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 1, 0, 0, 0,
        99, 33, 0, 0, 0, 0, 0, 0, 183, 0, 0, 0, 1, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 191, 22, 0,
        0, 0, 0, 0, 0, 97, 97, 0, 0, 0, 0, 0, 0, 21, 1, 2, 0, 5, 0, 0, 0, 97, 97, 0, 0, 0, 0, 0, 0,
        85, 1, 74, 0, 4, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 0, 0, 0, 0, 133, 0, 0,
        0, 59, 0, 0, 0, 97, 97, 28, 0, 0, 0, 0, 0, 99, 26, 240, 255, 0, 0, 0, 0, 97, 97, 68, 0, 0,
        0, 0, 0, 99, 26, 244, 255, 0, 0, 0, 0, 97, 98, 24, 0, 0, 0, 0, 0, 99, 42, 248, 255, 0, 0,
        0, 0, 97, 98, 64, 0, 0, 0, 0, 0, 220, 2, 0, 0, 32, 0, 0, 0, 99, 42, 252, 255, 0, 0, 0, 0,
        123, 42, 232, 255, 0, 0, 0, 0, 123, 26, 216, 255, 0, 0, 0, 0, 191, 161, 0, 0, 0, 0, 0, 0,
        7, 1, 0, 0, 240, 255, 255, 255, 123, 26, 208, 255, 0, 0, 0, 0, 191, 167, 0, 0, 0, 0, 0, 0,
        7, 7, 0, 0, 248, 255, 255, 255, 123, 122, 224, 255, 0, 0, 0, 0, 191, 163, 0, 0, 0, 0, 0, 0,
        7, 3, 0, 0, 208, 255, 255, 255, 24, 1, 0, 0, 106, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2,
        0, 0, 38, 0, 0, 0, 183, 4, 0, 0, 32, 0, 0, 0, 133, 0, 0, 0, 177, 0, 0, 0, 24, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 97, 17, 0, 0, 0, 0, 0, 0, 97, 162, 248, 255, 0, 0, 0, 0,
        93, 18, 42, 0, 0, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 97, 17, 0, 0,
        0, 0, 0, 0, 97, 162, 252, 255, 0, 0, 0, 0, 93, 18, 37, 0, 0, 0, 0, 0, 191, 163, 0, 0, 0, 0,
        0, 0, 7, 3, 0, 0, 240, 255, 255, 255, 191, 97, 0, 0, 0, 0, 0, 0, 24, 2, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 183, 4, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 70, 0, 0, 0, 101, 0, 14, 0,
        255, 255, 255, 255, 191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 240, 255, 255, 255, 123, 26,
        208, 255, 0, 0, 0, 0, 123, 122, 224, 255, 0, 0, 0, 0, 97, 161, 244, 255, 0, 0, 0, 0, 123,
        26, 216, 255, 0, 0, 0, 0, 97, 161, 252, 255, 0, 0, 0, 0, 123, 26, 232, 255, 0, 0, 0, 0,
        191, 163, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 208, 255, 255, 255, 24, 1, 0, 0, 144, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 47, 0, 0, 0, 5, 0, 13, 0, 0, 0, 0, 0, 191, 161, 0, 0, 0,
        0, 0, 0, 7, 1, 0, 0, 240, 255, 255, 255, 123, 26, 208, 255, 0, 0, 0, 0, 123, 122, 224, 255,
        0, 0, 0, 0, 97, 161, 244, 255, 0, 0, 0, 0, 123, 26, 216, 255, 0, 0, 0, 0, 97, 161, 252,
        255, 0, 0, 0, 0, 123, 26, 232, 255, 0, 0, 0, 0, 191, 163, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0,
        208, 255, 255, 255, 24, 1, 0, 0, 191, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 30, 0,
        0, 0, 183, 4, 0, 0, 32, 0, 0, 0, 133, 0, 0, 0, 177, 0, 0, 0, 183, 0, 0, 0, 1, 0, 0, 0, 149,
        0, 0, 0, 0, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 97, 16, 0, 0, 0, 0,
        0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 71, 80, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 80, 114, 111, 99,
        101, 115, 115, 105, 110, 103, 32, 37, 100, 66, 32, 109, 115, 103, 32, 102, 114, 111, 109,
        32, 91, 37, 112, 73, 52, 58, 37, 117, 45, 62, 37, 112, 73, 52, 58, 37, 117, 93, 32, 40,
        100, 111, 119, 110, 115, 116, 114, 101, 97, 109, 58, 32, 37, 100, 41, 0, 69, 82, 82, 79,
        82, 58, 32, 70, 97, 105, 108, 101, 100, 32, 116, 111, 32, 112, 97, 114, 115, 101, 32, 104,
        50, 32, 109, 101, 115, 115, 97, 103, 101, 58, 32, 37, 115, 0, 69, 115, 116, 97, 98, 108,
        105, 115, 104, 101, 100, 32, 115, 111, 99, 107, 101, 116, 32, 91, 37, 112, 73, 52, 58, 37,
        117, 45, 62, 37, 112, 73, 52, 58, 37, 117, 93, 0, 69, 82, 82, 79, 82, 58, 32, 70, 97, 105,
        108, 101, 100, 32, 116, 111, 32, 97, 100, 100, 32, 115, 111, 99, 107, 101, 116, 32, 91, 37,
        112, 73, 52, 58, 37, 117, 45, 62, 37, 112, 73, 52, 58, 37, 117, 93, 0, 65, 100, 100, 32,
        115, 111, 99, 107, 101, 116, 32, 91, 37, 112, 73, 52, 58, 37, 117, 45, 62, 37, 112, 73, 52,
        58, 37, 117, 93, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 104, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 30, 0, 0, 0, 136, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 31, 0, 0, 0, 16, 1, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 25, 0, 0, 0, 56, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 32, 0, 0, 0, 104, 1, 0, 0, 0,
        0, 0, 0, 10, 0, 0, 0, 28, 0, 0, 0, 144, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 25, 0, 0, 0, 8, 2,
        0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 33, 0, 0, 0, 24, 2, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 34, 0, 0,
        0, 80, 2, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 35, 0, 0, 0, 144, 2, 0, 0, 0, 0, 0, 0, 10, 0, 0,
        0, 26, 0, 0, 0, 144, 3, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 36, 0, 0, 0, 208, 3, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 36, 0, 0, 0, 248, 3, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 34, 0, 0, 0, 24, 4, 0,
        0, 0, 0, 0, 0, 10, 0, 0, 0, 27, 0, 0, 0, 80, 4, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 32, 0, 0, 0,
        112, 4, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 37, 0, 0, 0, 216, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        25, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 30, 0, 0, 0, 40, 1, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 31, 0, 0, 0, 104, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 39, 0, 0, 0, 224, 1, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 25, 0, 0, 0, 80, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 25, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 37, 0, 0, 0, 159, 235, 1, 0, 24, 0, 0, 0, 0, 0, 0, 0, 164,
        10, 0, 0, 164, 10, 0, 0, 209, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0,
        0, 1, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 6,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 2, 8, 0, 0, 0, 25, 0, 0, 0, 2, 0, 0, 4, 16, 0, 0, 0, 34, 0, 0, 0, 9, 0, 0, 0,
        0, 0, 0, 0, 40, 0, 0, 0, 9, 0, 0, 0, 64, 0, 0, 0, 47, 0, 0, 0, 2, 0, 0, 4, 8, 0, 0, 0, 56,
        0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 60, 0, 0, 0, 10, 0, 0, 0, 32, 0, 0, 0, 65, 0, 0, 0, 0, 0,
        0, 8, 11, 0, 0, 0, 69, 0, 0, 0, 0, 0, 0, 8, 12, 0, 0, 0, 75, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0,
        0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 4, 32, 0, 0, 0,
        88, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 93, 0, 0, 0, 5, 0, 0, 0, 64, 0, 0, 0, 105, 0, 0, 0, 7,
        0, 0, 0, 128, 0, 0, 0, 109, 0, 0, 0, 13, 0, 0, 0, 192, 0, 0, 0, 115, 0, 0, 0, 0, 0, 0, 14,
        14, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0,
        0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 10, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 2, 21, 0, 0, 0, 130, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 3, 0, 0, 0, 0, 20, 0, 0, 0, 4, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 4, 32, 0,
        0, 0, 88, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 93, 0, 0, 0, 16, 0, 0, 0, 64, 0, 0, 0, 105, 0,
        0, 0, 18, 0, 0, 0, 128, 0, 0, 0, 109, 0, 0, 0, 19, 0, 0, 0, 192, 0, 0, 0, 135, 0, 0, 0, 0,
        0, 0, 14, 22, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 18, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 4, 32, 0, 0, 0,
        88, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 93, 0, 0, 0, 5, 0, 0, 0, 64, 0, 0, 0, 105, 0, 0, 0,
        7, 0, 0, 0, 128, 0, 0, 0, 109, 0, 0, 0, 13, 0, 0, 0, 192, 0, 0, 0, 143, 0, 0, 0, 0, 0, 0,
        14, 26, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 29, 0, 0, 0, 152, 0, 0, 0, 11, 0, 0,
        4, 80, 0, 0, 0, 0, 0, 0, 0, 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 64, 0, 0, 0,
        162, 0, 0, 0, 11, 0, 0, 0, 128, 0, 0, 0, 169, 0, 0, 0, 11, 0, 0, 0, 160, 0, 0, 0, 180, 0,
        0, 0, 11, 0, 0, 0, 192, 0, 0, 0, 190, 0, 0, 0, 33, 0, 0, 0, 224, 0, 0, 0, 201, 0, 0, 0, 33,
        0, 0, 0, 96, 1, 0, 0, 211, 0, 0, 0, 11, 0, 0, 0, 224, 1, 0, 0, 223, 0, 0, 0, 11, 0, 0, 0,
        0, 2, 0, 0, 234, 0, 0, 0, 11, 0, 0, 0, 32, 2, 0, 0, 0, 0, 0, 0, 34, 0, 0, 0, 64, 2, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 5, 8, 0, 0, 0, 239, 0, 0, 0, 31, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 5, 8, 0, 0, 0, 244, 0, 0, 0, 31, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 11, 0, 0, 0, 4, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 5, 8, 0, 0, 0, 253, 0, 0, 0, 35, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 62,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 8, 37, 0, 0, 0, 3, 1, 0, 0, 0, 0, 0, 8, 38, 0, 0, 0, 8, 1, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 40, 0, 0, 0, 22, 1, 0, 0, 2,
        0, 0, 4, 16, 0, 0, 0, 30, 1, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 34, 1, 0, 0, 41, 0, 0, 0, 64,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 36, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 13, 2, 0, 0, 0, 38, 1,
        0, 0, 28, 0, 0, 0, 42, 1, 0, 0, 36, 0, 0, 0, 46, 1, 0, 0, 39, 0, 0, 0, 50, 1, 0, 0, 1, 0,
        0, 12, 42, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 13, 2, 0, 0, 0, 38, 1, 0, 0, 28, 0, 0, 0, 64, 1,
        0, 0, 1, 0, 0, 12, 44, 0, 0, 0, 73, 1, 0, 0, 1, 0, 0, 12, 44, 0, 0, 0, 82, 1, 0, 0, 1, 0,
        0, 12, 44, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 13, 2, 0, 0, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, 0,
        0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 50, 0, 0, 0, 94, 1, 0, 0, 1,
        0, 0, 4, 8, 0, 0, 0, 107, 1, 0, 0, 53, 0, 0, 0, 0, 0, 0, 0, 116, 1, 0, 0, 0, 0, 0, 8, 52,
        0, 0, 0, 122, 1, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0,
        0, 0, 51, 0, 0, 0, 4, 0, 0, 0, 1, 0, 0, 0, 141, 1, 0, 0, 2, 0, 0, 12, 48, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 13, 13, 0, 0, 0, 0, 0, 0, 0, 49, 0, 0, 0, 158, 1, 0, 0, 2, 0, 0, 12, 55, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 49, 0, 0, 0, 176, 1, 0, 0, 2, 0, 0, 12,
        57, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 60, 0, 0, 0, 197, 1, 0, 0, 41, 0, 0, 4, 224, 0, 0, 0,
        210, 1, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 61, 0, 0, 0, 32, 0, 0, 0, 162, 0, 0, 0,
        11, 0, 0, 0, 160, 0, 0, 0, 169, 0, 0, 0, 11, 0, 0, 0, 192, 0, 0, 0, 180, 0, 0, 0, 11, 0, 0,
        0, 224, 0, 0, 0, 190, 0, 0, 0, 33, 0, 0, 0, 0, 1, 0, 0, 201, 0, 0, 0, 33, 0, 0, 0, 128, 1,
        0, 0, 211, 0, 0, 0, 11, 0, 0, 0, 0, 2, 0, 0, 223, 0, 0, 0, 11, 0, 0, 0, 32, 2, 0, 0, 213,
        1, 0, 0, 11, 0, 0, 0, 64, 2, 0, 0, 225, 1, 0, 0, 11, 0, 0, 0, 96, 2, 0, 0, 234, 1, 0, 0,
        11, 0, 0, 0, 128, 2, 0, 0, 242, 1, 0, 0, 11, 0, 0, 0, 160, 2, 0, 0, 8, 2, 0, 0, 11, 0, 0,
        0, 192, 2, 0, 0, 14, 2, 0, 0, 11, 0, 0, 0, 224, 2, 0, 0, 22, 2, 0, 0, 11, 0, 0, 0, 0, 3, 0,
        0, 35, 2, 0, 0, 11, 0, 0, 0, 32, 3, 0, 0, 43, 2, 0, 0, 11, 0, 0, 0, 64, 3, 0, 0, 51, 2, 0,
        0, 11, 0, 0, 0, 96, 3, 0, 0, 59, 2, 0, 0, 11, 0, 0, 0, 128, 3, 0, 0, 69, 2, 0, 0, 11, 0, 0,
        0, 160, 3, 0, 0, 79, 2, 0, 0, 11, 0, 0, 0, 192, 3, 0, 0, 94, 2, 0, 0, 11, 0, 0, 0, 224, 3,
        0, 0, 111, 2, 0, 0, 11, 0, 0, 0, 0, 4, 0, 0, 123, 2, 0, 0, 11, 0, 0, 0, 32, 4, 0, 0, 135,
        2, 0, 0, 11, 0, 0, 0, 64, 4, 0, 0, 149, 2, 0, 0, 11, 0, 0, 0, 96, 4, 0, 0, 157, 2, 0, 0,
        11, 0, 0, 0, 128, 4, 0, 0, 170, 2, 0, 0, 11, 0, 0, 0, 160, 4, 0, 0, 179, 2, 0, 0, 11, 0, 0,
        0, 192, 4, 0, 0, 193, 2, 0, 0, 11, 0, 0, 0, 224, 4, 0, 0, 202, 2, 0, 0, 11, 0, 0, 0, 0, 5,
        0, 0, 213, 2, 0, 0, 11, 0, 0, 0, 32, 5, 0, 0, 223, 2, 0, 0, 51, 0, 0, 0, 64, 5, 0, 0, 238,
        2, 0, 0, 51, 0, 0, 0, 128, 5, 0, 0, 0, 0, 0, 0, 34, 0, 0, 0, 192, 5, 0, 0, 0, 0, 0, 0, 67,
        0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 68, 0, 0, 0, 64, 6, 0, 0, 250, 2, 0, 0, 11, 0, 0, 0, 128,
        6, 0, 0, 2, 3, 0, 0, 11, 0, 0, 0, 160, 6, 0, 0, 16, 3, 0, 0, 51, 0, 0, 0, 192, 6, 0, 0, 0,
        0, 0, 0, 3, 0, 0, 5, 16, 0, 0, 0, 29, 3, 0, 0, 33, 0, 0, 0, 0, 0, 0, 0, 34, 3, 0, 0, 11, 0,
        0, 0, 0, 0, 0, 0, 40, 3, 0, 0, 33, 0, 0, 0, 0, 0, 0, 0, 50, 3, 0, 0, 14, 0, 0, 4, 80, 0, 0,
        0, 59, 3, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 162, 0, 0, 0, 11, 0, 0, 0, 32, 0, 0, 0, 88, 0, 0,
        0, 11, 0, 0, 0, 64, 0, 0, 0, 72, 3, 0, 0, 11, 0, 0, 0, 96, 0, 0, 0, 81, 3, 0, 0, 11, 0, 0,
        0, 128, 0, 0, 0, 86, 3, 0, 0, 11, 0, 0, 0, 160, 0, 0, 0, 95, 3, 0, 0, 11, 0, 0, 0, 192, 0,
        0, 0, 103, 3, 0, 0, 33, 0, 0, 0, 224, 0, 0, 0, 111, 3, 0, 0, 11, 0, 0, 0, 96, 1, 0, 0, 120,
        3, 0, 0, 63, 0, 0, 0, 128, 1, 0, 0, 129, 3, 0, 0, 11, 0, 0, 0, 160, 1, 0, 0, 137, 3, 0, 0,
        33, 0, 0, 0, 192, 1, 0, 0, 8, 2, 0, 0, 11, 0, 0, 0, 64, 2, 0, 0, 145, 3, 0, 0, 66, 0, 0, 0,
        96, 2, 0, 0, 162, 3, 0, 0, 0, 0, 0, 8, 64, 0, 0, 0, 169, 3, 0, 0, 0, 0, 0, 8, 65, 0, 0, 0,
        175, 3, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 16, 0, 0, 0, 190, 3, 0, 0, 0, 0, 0, 8, 2, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 5, 8, 0, 0, 0, 196, 3, 0, 0, 31, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 5, 8, 0, 0, 0, 205, 3, 0, 0, 31, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 13, 2, 0, 0,
        0, 218, 3, 0, 0, 59, 0, 0, 0, 222, 3, 0, 0, 1, 0, 0, 12, 69, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        13, 2, 0, 0, 0, 238, 3, 0, 0, 1, 0, 0, 12, 71, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0,
        20, 0, 0, 0, 4, 0, 0, 0, 4, 0, 0, 0, 5, 4, 0, 0, 0, 0, 0, 14, 73, 0, 0, 0, 1, 0, 0, 0, 13,
        4, 0, 0, 0, 0, 0, 14, 10, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 77, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 9, 10, 0, 0, 0, 56, 0, 0, 0, 0, 0, 0, 14, 76, 0, 0, 0, 1, 0, 0, 0, 60, 0, 0,
        0, 0, 0, 0, 14, 76, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 20, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 3, 0, 0, 0, 0, 80, 0, 0, 0, 4, 0, 0, 0, 60, 0, 0, 0, 32, 4, 0, 0, 0, 0, 0, 14, 81,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 80, 0, 0, 0, 4, 0, 0, 0, 38, 0, 0,
        0, 51, 4, 0, 0, 0, 0, 0, 14, 83, 0, 0, 0, 0, 0, 0, 0, 71, 4, 0, 0, 0, 0, 0, 14, 83, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 80, 0, 0, 0, 4, 0, 0, 0, 47, 0, 0, 0,
        94, 4, 0, 0, 0, 0, 0, 14, 86, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 80,
        0, 0, 0, 4, 0, 0, 0, 30, 0, 0, 0, 119, 4, 0, 0, 0, 0, 0, 14, 88, 0, 0, 0, 0, 0, 0, 0, 146,
        15, 0, 0, 1, 0, 0, 15, 4, 0, 0, 0, 74, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 154, 15, 0, 0, 1,
        0, 0, 15, 4, 0, 0, 0, 75, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 159, 15, 0, 0, 7, 0, 0, 15, 221,
        0, 0, 0, 78, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 79, 0, 0, 0, 4, 0, 0, 0, 4, 0, 0, 0, 82, 0,
        0, 0, 8, 0, 0, 0, 60, 0, 0, 0, 84, 0, 0, 0, 68, 0, 0, 0, 38, 0, 0, 0, 85, 0, 0, 0, 106, 0,
        0, 0, 38, 0, 0, 0, 87, 0, 0, 0, 144, 0, 0, 0, 47, 0, 0, 0, 89, 0, 0, 0, 191, 0, 0, 0, 30,
        0, 0, 0, 167, 15, 0, 0, 3, 0, 0, 15, 96, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 23,
        0, 0, 0, 32, 0, 0, 0, 32, 0, 0, 0, 27, 0, 0, 0, 64, 0, 0, 0, 32, 0, 0, 0, 173, 15, 0, 0, 3,
        0, 0, 15, 0, 0, 0, 0, 54, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 56, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 105, 110, 116, 0, 95, 95, 65, 82, 82, 65, 89,
        95, 83, 73, 90, 69, 95, 84, 89, 80, 69, 95, 95, 0, 115, 111, 99, 107, 95, 107, 101, 121, 0,
        108, 111, 99, 97, 108, 0, 114, 101, 109, 111, 116, 101, 0, 97, 100, 100, 114, 95, 107, 101,
        121, 0, 105, 112, 52, 0, 112, 111, 114, 116, 0, 117, 51, 50, 0, 95, 95, 117, 51, 50, 0,
        117, 110, 115, 105, 103, 110, 101, 100, 32, 105, 110, 116, 0, 116, 121, 112, 101, 0, 109,
        97, 120, 95, 101, 110, 116, 114, 105, 101, 115, 0, 107, 101, 121, 0, 118, 97, 108, 117,
        101, 0, 117, 112, 103, 114, 97, 100, 101, 100, 95, 99, 111, 110, 110, 115, 0, 99, 104, 97,
        114, 0, 109, 97, 116, 99, 104, 101, 115, 0, 115, 111, 99, 107, 95, 109, 97, 112, 0, 115,
        107, 95, 109, 115, 103, 95, 109, 100, 0, 102, 97, 109, 105, 108, 121, 0, 114, 101, 109,
        111, 116, 101, 95, 105, 112, 52, 0, 108, 111, 99, 97, 108, 95, 105, 112, 52, 0, 114, 101,
        109, 111, 116, 101, 95, 105, 112, 54, 0, 108, 111, 99, 97, 108, 95, 105, 112, 54, 0, 114,
        101, 109, 111, 116, 101, 95, 112, 111, 114, 116, 0, 108, 111, 99, 97, 108, 95, 112, 111,
        114, 116, 0, 115, 105, 122, 101, 0, 100, 97, 116, 97, 0, 100, 97, 116, 97, 95, 101, 110,
        100, 0, 115, 107, 0, 117, 56, 0, 95, 95, 117, 56, 0, 117, 110, 115, 105, 103, 110, 101,
        100, 32, 99, 104, 97, 114, 0, 104, 100, 114, 95, 115, 116, 114, 0, 108, 101, 110, 0, 112,
        116, 114, 0, 109, 115, 103, 0, 105, 100, 120, 0, 115, 116, 114, 0, 101, 120, 116, 114, 97,
        99, 116, 95, 109, 97, 116, 99, 104, 0, 112, 97, 114, 115, 101, 95, 104, 49, 0, 112, 97,
        114, 115, 101, 95, 104, 50, 0, 109, 115, 103, 95, 118, 101, 114, 100, 105, 99, 116, 0, 98,
        112, 102, 95, 105, 116, 101, 114, 95, 110, 117, 109, 0, 95, 95, 111, 112, 97, 113, 117,
        101, 0, 95, 95, 117, 54, 52, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 108, 111, 110,
        103, 32, 108, 111, 110, 103, 0, 98, 112, 102, 95, 105, 116, 101, 114, 95, 110, 117, 109,
        95, 110, 101, 119, 0, 98, 112, 102, 95, 105, 116, 101, 114, 95, 110, 117, 109, 95, 110,
        101, 120, 116, 0, 98, 112, 102, 95, 105, 116, 101, 114, 95, 110, 117, 109, 95, 100, 101,
        115, 116, 114, 111, 121, 0, 98, 112, 102, 95, 115, 111, 99, 107, 95, 111, 112, 115, 0, 111,
        112, 0, 105, 115, 95, 102, 117, 108, 108, 115, 111, 99, 107, 0, 115, 110, 100, 95, 99, 119,
        110, 100, 0, 115, 114, 116, 116, 95, 117, 115, 0, 98, 112, 102, 95, 115, 111, 99, 107, 95,
        111, 112, 115, 95, 99, 98, 95, 102, 108, 97, 103, 115, 0, 115, 116, 97, 116, 101, 0, 114,
        116, 116, 95, 109, 105, 110, 0, 115, 110, 100, 95, 115, 115, 116, 104, 114, 101, 115, 104,
        0, 114, 99, 118, 95, 110, 120, 116, 0, 115, 110, 100, 95, 110, 120, 116, 0, 115, 110, 100,
        95, 117, 110, 97, 0, 109, 115, 115, 95, 99, 97, 99, 104, 101, 0, 101, 99, 110, 95, 102,
        108, 97, 103, 115, 0, 114, 97, 116, 101, 95, 100, 101, 108, 105, 118, 101, 114, 101, 100,
        0, 114, 97, 116, 101, 95, 105, 110, 116, 101, 114, 118, 97, 108, 95, 117, 115, 0, 112, 97,
        99, 107, 101, 116, 115, 95, 111, 117, 116, 0, 114, 101, 116, 114, 97, 110, 115, 95, 111,
        117, 116, 0, 116, 111, 116, 97, 108, 95, 114, 101, 116, 114, 97, 110, 115, 0, 115, 101,
        103, 115, 95, 105, 110, 0, 100, 97, 116, 97, 95, 115, 101, 103, 115, 95, 105, 110, 0, 115,
        101, 103, 115, 95, 111, 117, 116, 0, 100, 97, 116, 97, 95, 115, 101, 103, 115, 95, 111,
        117, 116, 0, 108, 111, 115, 116, 95, 111, 117, 116, 0, 115, 97, 99, 107, 101, 100, 95, 111,
        117, 116, 0, 115, 107, 95, 116, 120, 104, 97, 115, 104, 0, 98, 121, 116, 101, 115, 95, 114,
        101, 99, 101, 105, 118, 101, 100, 0, 98, 121, 116, 101, 115, 95, 97, 99, 107, 101, 100, 0,
        115, 107, 98, 95, 108, 101, 110, 0, 115, 107, 98, 95, 116, 99, 112, 95, 102, 108, 97, 103,
        115, 0, 115, 107, 98, 95, 104, 119, 116, 115, 116, 97, 109, 112, 0, 97, 114, 103, 115, 0,
        114, 101, 112, 108, 121, 0, 114, 101, 112, 108, 121, 108, 111, 110, 103, 0, 98, 112, 102,
        95, 115, 111, 99, 107, 0, 98, 111, 117, 110, 100, 95, 100, 101, 118, 95, 105, 102, 0, 112,
        114, 111, 116, 111, 99, 111, 108, 0, 109, 97, 114, 107, 0, 112, 114, 105, 111, 114, 105,
        116, 121, 0, 115, 114, 99, 95, 105, 112, 52, 0, 115, 114, 99, 95, 105, 112, 54, 0, 115,
        114, 99, 95, 112, 111, 114, 116, 0, 100, 115, 116, 95, 112, 111, 114, 116, 0, 100, 115,
        116, 95, 105, 112, 52, 0, 100, 115, 116, 95, 105, 112, 54, 0, 114, 120, 95, 113, 117, 101,
        117, 101, 95, 109, 97, 112, 112, 105, 110, 103, 0, 95, 95, 98, 101, 49, 54, 0, 95, 95, 117,
        49, 54, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 115, 104, 111, 114, 116, 0, 95, 95,
        115, 51, 50, 0, 115, 107, 98, 95, 100, 97, 116, 97, 0, 115, 107, 98, 95, 100, 97, 116, 97,
        95, 101, 110, 100, 0, 111, 112, 115, 0, 109, 111, 110, 105, 116, 111, 114, 95, 115, 111,
        99, 107, 101, 116, 115, 0, 103, 101, 116, 95, 110, 117, 109, 95, 117, 112, 103, 114, 97,
        100, 101, 100, 95, 99, 111, 110, 110, 115, 0, 76, 73, 67, 69, 78, 83, 69, 0, 110, 117, 109,
        95, 117, 112, 103, 114, 97, 100, 101, 100, 95, 99, 111, 110, 110, 115, 0, 109, 115, 103,
        95, 118, 101, 114, 100, 105, 99, 116, 46, 95, 95, 95, 102, 109, 116, 0, 109, 115, 103, 95,
        118, 101, 114, 100, 105, 99, 116, 46, 95, 95, 95, 95, 102, 109, 116, 0, 109, 111, 110, 105,
        116, 111, 114, 95, 115, 111, 99, 107, 101, 116, 115, 46, 95, 95, 95, 102, 109, 116, 0, 109,
        111, 110, 105, 116, 111, 114, 95, 115, 111, 99, 107, 101, 116, 115, 46, 95, 95, 95, 102,
        109, 116, 46, 49, 0, 109, 111, 110, 105, 116, 111, 114, 95, 115, 111, 99, 107, 101, 116,
        115, 46, 95, 95, 95, 102, 109, 116, 46, 50, 0, 47, 108, 111, 99, 97, 108, 47, 104, 111,
        109, 101, 47, 108, 97, 117, 114, 105, 110, 98, 47, 112, 114, 111, 106, 115, 47, 98, 101,
        101, 108, 105, 110, 101, 45, 114, 115, 47, 117, 116, 105, 108, 115, 47, 115, 114, 99, 47,
        112, 114, 111, 103, 46, 98, 112, 102, 46, 99, 0, 95, 95, 110, 111, 105, 110, 108, 105, 110,
        101, 32, 105, 110, 116, 32, 101, 120, 116, 114, 97, 99, 116, 95, 109, 97, 116, 99, 104, 40,
        115, 116, 114, 117, 99, 116, 32, 115, 107, 95, 109, 115, 103, 95, 109, 100, 32, 42, 109,
        115, 103, 44, 32, 117, 56, 32, 105, 100, 120, 44, 32, 115, 116, 114, 117, 99, 116, 32, 104,
        100, 114, 95, 115, 116, 114, 42, 32, 115, 116, 114, 41, 32, 123, 0, 32, 32, 32, 32, 105,
        110, 116, 32, 114, 101, 116, 32, 61, 32, 45, 49, 59, 0, 9, 95, 95, 115, 105, 110, 107, 40,
        109, 115, 103, 41, 59, 0, 9, 95, 95, 115, 105, 110, 107, 40, 105, 100, 120, 41, 59, 0, 9,
        95, 95, 115, 105, 110, 107, 40, 115, 116, 114, 41, 59, 0, 9, 95, 95, 115, 105, 110, 107,
        40, 114, 101, 116, 41, 59, 0, 9, 98, 112, 102, 95, 109, 115, 103, 95, 112, 117, 108, 108,
        95, 100, 97, 116, 97, 40, 109, 115, 103, 44, 32, 48, 44, 32, 109, 115, 103, 45, 62, 115,
        105, 122, 101, 44, 32, 48, 41, 59, 0, 9, 114, 101, 116, 117, 114, 110, 32, 114, 101, 116,
        59, 0, 95, 95, 110, 111, 105, 110, 108, 105, 110, 101, 32, 105, 110, 116, 32, 112, 97, 114,
        115, 101, 95, 104, 49, 40, 115, 116, 114, 117, 99, 116, 32, 115, 107, 95, 109, 115, 103,
        95, 109, 100, 32, 42, 109, 115, 103, 41, 32, 123, 0, 32, 32, 32, 9, 105, 110, 116, 32, 114,
        101, 116, 32, 61, 32, 45, 49, 59, 0, 95, 95, 110, 111, 105, 110, 108, 105, 110, 101, 32,
        105, 110, 116, 32, 112, 97, 114, 115, 101, 95, 104, 50, 40, 115, 116, 114, 117, 99, 116,
        32, 115, 107, 95, 109, 115, 103, 95, 109, 100, 32, 42, 109, 115, 103, 41, 32, 123, 0, 105,
        110, 116, 32, 109, 115, 103, 95, 118, 101, 114, 100, 105, 99, 116, 40, 115, 116, 114, 117,
        99, 116, 32, 115, 107, 95, 109, 115, 103, 95, 109, 100, 32, 42, 109, 115, 103, 41, 32, 123,
        0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 46, 105, 112, 52, 32, 61, 32, 109, 115,
        103, 45, 62, 108, 111, 99, 97, 108, 95, 105, 112, 52, 44, 0, 32, 32, 32, 32, 32, 32, 32,
        32, 46, 108, 111, 99, 97, 108, 32, 61, 32, 123, 0, 32, 32, 32, 32, 115, 116, 114, 117, 99,
        116, 32, 115, 111, 99, 107, 95, 107, 101, 121, 32, 105, 107, 101, 121, 32, 61, 32, 123, 0,
        32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 46, 112, 111, 114, 116, 32, 61, 32, 109,
        115, 103, 45, 62, 108, 111, 99, 97, 108, 95, 112, 111, 114, 116, 0, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 46, 105, 112, 52, 32, 61, 32, 109, 115, 103, 45, 62, 114, 101, 109,
        111, 116, 101, 95, 105, 112, 52, 44, 0, 32, 32, 32, 32, 32, 32, 32, 32, 46, 114, 101, 109,
        111, 116, 101, 32, 61, 32, 123, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 46, 112,
        111, 114, 116, 32, 61, 32, 98, 112, 102, 95, 110, 116, 111, 104, 108, 40, 109, 115, 103,
        45, 62, 114, 101, 109, 111, 116, 101, 95, 112, 111, 114, 116, 41, 0, 32, 32, 32, 32, 98,
        111, 111, 108, 32, 105, 115, 95, 100, 111, 119, 110, 115, 116, 114, 101, 97, 109, 32, 61,
        32, 40, 105, 107, 101, 121, 46, 114, 101, 109, 111, 116, 101, 46, 105, 112, 52, 32, 61, 61,
        32, 105, 112, 52, 32, 38, 38, 32, 105, 107, 101, 121, 46, 114, 101, 109, 111, 116, 101, 46,
        112, 111, 114, 116, 32, 61, 61, 32, 112, 111, 114, 116, 41, 59, 0, 32, 32, 32, 32, 98, 112,
        102, 95, 112, 114, 105, 110, 116, 107, 40, 34, 80, 114, 111, 99, 101, 115, 115, 105, 110,
        103, 32, 37, 100, 66, 32, 109, 115, 103, 32, 102, 114, 111, 109, 32, 91, 37, 112, 73, 52,
        58, 37, 117, 45, 62, 37, 112, 73, 52, 58, 37, 117, 93, 32, 40, 100, 111, 119, 110, 115,
        116, 114, 101, 97, 109, 58, 32, 37, 100, 41, 34, 44, 32, 109, 115, 103, 45, 62, 115, 105,
        122, 101, 44, 32, 38, 105, 107, 101, 121, 46, 108, 111, 99, 97, 108, 46, 105, 112, 52, 44,
        32, 105, 107, 101, 121, 46, 108, 111, 99, 97, 108, 46, 112, 111, 114, 116, 44, 32, 38, 105,
        107, 101, 121, 46, 114, 101, 109, 111, 116, 101, 46, 105, 112, 52, 44, 32, 105, 107, 101,
        121, 46, 114, 101, 109, 111, 116, 101, 46, 112, 111, 114, 116, 44, 32, 105, 115, 95, 100,
        111, 119, 110, 115, 116, 114, 101, 97, 109, 41, 59, 0, 32, 32, 32, 32, 98, 111, 111, 108,
        32, 105, 115, 95, 104, 50, 32, 61, 32, 40, 98, 112, 102, 95, 109, 97, 112, 95, 108, 111,
        111, 107, 117, 112, 95, 101, 108, 101, 109, 40, 38, 117, 112, 103, 114, 97, 100, 101, 100,
        95, 99, 111, 110, 110, 115, 44, 32, 38, 105, 107, 101, 121, 41, 32, 33, 61, 32, 78, 85, 76,
        76, 41, 59, 0, 32, 32, 32, 32, 105, 102, 32, 40, 105, 115, 95, 104, 50, 41, 32, 123, 0, 32,
        32, 32, 32, 32, 32, 32, 32, 105, 110, 116, 32, 100, 111, 110, 101, 95, 105, 100, 120, 32,
        61, 32, 112, 97, 114, 115, 101, 95, 104, 50, 40, 109, 115, 103, 41, 59, 0, 32, 32, 32, 32,
        32, 32, 32, 32, 105, 102, 32, 40, 100, 111, 110, 101, 95, 105, 100, 120, 32, 60, 32, 48,
        41, 32, 123, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 98, 112, 102, 95, 112, 114,
        105, 110, 116, 107, 40, 34, 69, 82, 82, 79, 82, 58, 32, 70, 97, 105, 108, 101, 100, 32,
        116, 111, 32, 112, 97, 114, 115, 101, 32, 104, 50, 32, 109, 101, 115, 115, 97, 103, 101,
        58, 32, 37, 115, 34, 44, 32, 109, 115, 103, 45, 62, 100, 97, 116, 97, 41, 59, 0, 32, 32,
        32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 100, 111, 110, 101, 95, 105, 100, 120, 32, 62,
        32, 57, 41, 32, 123, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 117, 51, 50, 32,
        105, 32, 61, 32, 48, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 98, 112, 102,
        95, 102, 111, 114, 40, 105, 44, 32, 48, 44, 32, 51, 50, 41, 32, 123, 0, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 115, 116, 114, 117, 99, 116, 32, 104, 100, 114,
        95, 115, 116, 114, 32, 115, 116, 114, 32, 61, 32, 123, 32, 48, 32, 125, 59, 0, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 101, 120, 116, 114,
        97, 99, 116, 95, 109, 97, 116, 99, 104, 40, 109, 115, 103, 44, 32, 105, 44, 32, 38, 115,
        116, 114, 41, 32, 61, 61, 32, 48, 41, 32, 123, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 117, 49, 54, 32, 108, 101, 110, 32, 61, 32, 115,
        116, 114, 46, 108, 101, 110, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 98, 112, 102, 95, 112, 114, 111, 98, 101, 95, 114, 101, 97, 100,
        95, 107, 101, 114, 110, 101, 108, 40, 116, 109, 112, 44, 32, 108, 101, 110, 44, 32, 115,
        116, 114, 46, 112, 116, 114, 41, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 32, 99, 104, 97, 114, 32, 116, 109, 112, 91, 49, 50, 56, 93, 32,
        61, 32, 123, 48, 125, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 98, 112, 102, 95, 109, 97, 112, 95, 117, 112, 100, 97, 116, 101, 95,
        101, 108, 101, 109, 40, 38, 109, 97, 116, 99, 104, 101, 115, 44, 32, 38, 105, 44, 32, 116,
        109, 112, 44, 32, 66, 80, 70, 95, 65, 78, 89, 41, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 98, 112, 102, 95, 109, 97, 112, 95, 100,
        101, 108, 101, 116, 101, 95, 101, 108, 101, 109, 40, 38, 109, 97, 116, 99, 104, 101, 115,
        44, 32, 38, 105, 41, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 105, 110, 116, 32, 100, 111,
        110, 101, 95, 105, 100, 120, 32, 61, 32, 112, 97, 114, 115, 101, 95, 104, 49, 40, 109, 115,
        103, 41, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 105, 110, 116, 32, 102,
        108, 97, 103, 32, 61, 32, 49, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 98,
        112, 102, 95, 109, 97, 112, 95, 117, 112, 100, 97, 116, 101, 95, 101, 108, 101, 109, 40,
        38, 117, 112, 103, 114, 97, 100, 101, 100, 95, 99, 111, 110, 110, 115, 44, 32, 38, 105,
        107, 101, 121, 44, 32, 38, 102, 108, 97, 103, 44, 32, 66, 80, 70, 95, 65, 78, 89, 41, 59,
        0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 110, 117, 109, 95, 117, 112, 103, 114,
        97, 100, 101, 100, 95, 99, 111, 110, 110, 115, 32, 43, 61, 32, 49, 59, 0, 125, 0, 105, 110,
        116, 32, 109, 111, 110, 105, 116, 111, 114, 95, 115, 111, 99, 107, 101, 116, 115, 40, 115,
        116, 114, 117, 99, 116, 32, 98, 112, 102, 95, 115, 111, 99, 107, 95, 111, 112, 115, 32, 42,
        111, 112, 115, 41, 32, 123, 0, 32, 32, 32, 32, 105, 102, 32, 40, 111, 112, 115, 45, 62,
        111, 112, 32, 61, 61, 32, 66, 80, 70, 95, 83, 79, 67, 75, 95, 79, 80, 83, 95, 80, 65, 83,
        83, 73, 86, 69, 95, 69, 83, 84, 65, 66, 76, 73, 83, 72, 69, 68, 95, 67, 66, 32, 124, 124,
        32, 111, 112, 115, 45, 62, 111, 112, 32, 61, 61, 32, 66, 80, 70, 95, 83, 79, 67, 75, 95,
        79, 80, 83, 95, 65, 67, 84, 73, 86, 69, 95, 69, 83, 84, 65, 66, 76, 73, 83, 72, 69, 68, 95,
        67, 66, 41, 32, 123, 0, 32, 32, 32, 32, 32, 32, 32, 32, 98, 112, 102, 95, 115, 111, 99,
        107, 95, 111, 112, 115, 95, 99, 98, 95, 102, 108, 97, 103, 115, 95, 115, 101, 116, 40, 111,
        112, 115, 44, 32, 48, 41, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 46, 105, 112, 52, 32, 61, 32, 111, 112, 115, 45, 62, 108, 111, 99, 97, 108, 95,
        105, 112, 52, 44, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 46, 108, 111, 99, 97,
        108, 32, 61, 32, 123, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        46, 112, 111, 114, 116, 32, 61, 32, 111, 112, 115, 45, 62, 108, 111, 99, 97, 108, 95, 112,
        111, 114, 116, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 46, 105,
        112, 52, 32, 61, 32, 111, 112, 115, 45, 62, 114, 101, 109, 111, 116, 101, 95, 105, 112, 52,
        44, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 46, 114, 101, 109, 111, 116, 101,
        32, 61, 32, 123, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 46,
        112, 111, 114, 116, 32, 61, 32, 98, 112, 102, 95, 110, 116, 111, 104, 108, 40, 111, 112,
        115, 45, 62, 114, 101, 109, 111, 116, 101, 95, 112, 111, 114, 116, 41, 0, 32, 32, 32, 32,
        32, 32, 32, 32, 98, 112, 102, 95, 112, 114, 105, 110, 116, 107, 40, 34, 69, 115, 116, 97,
        98, 108, 105, 115, 104, 101, 100, 32, 115, 111, 99, 107, 101, 116, 32, 91, 37, 112, 73, 52,
        58, 37, 117, 45, 62, 37, 112, 73, 52, 58, 37, 117, 93, 34, 44, 32, 38, 115, 107, 101, 121,
        46, 108, 111, 99, 97, 108, 46, 105, 112, 52, 44, 32, 115, 107, 101, 121, 46, 108, 111, 99,
        97, 108, 46, 112, 111, 114, 116, 44, 32, 38, 115, 107, 101, 121, 46, 114, 101, 109, 111,
        116, 101, 46, 105, 112, 52, 44, 32, 115, 107, 101, 121, 46, 114, 101, 109, 111, 116, 101,
        46, 112, 111, 114, 116, 41, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 115, 116, 114, 117, 99,
        116, 32, 115, 111, 99, 107, 95, 107, 101, 121, 32, 115, 107, 101, 121, 32, 61, 32, 123, 0,
        32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 115, 107, 101, 121, 46, 114, 101, 109,
        111, 116, 101, 46, 105, 112, 52, 32, 61, 61, 32, 105, 112, 52, 32, 38, 38, 32, 115, 107,
        101, 121, 46, 114, 101, 109, 111, 116, 101, 46, 112, 111, 114, 116, 32, 61, 61, 32, 112,
        111, 114, 116, 41, 32, 123, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102,
        32, 40, 98, 112, 102, 95, 115, 111, 99, 107, 95, 104, 97, 115, 104, 95, 117, 112, 100, 97,
        116, 101, 40, 111, 112, 115, 44, 32, 38, 115, 111, 99, 107, 95, 109, 97, 112, 44, 32, 38,
        115, 107, 101, 121, 44, 32, 66, 80, 70, 95, 65, 78, 89, 41, 32, 60, 32, 48, 41, 32, 123, 0,
        32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 98, 112, 102, 95, 112, 114,
        105, 110, 116, 107, 40, 34, 69, 82, 82, 79, 82, 58, 32, 70, 97, 105, 108, 101, 100, 32,
        116, 111, 32, 97, 100, 100, 32, 115, 111, 99, 107, 101, 116, 32, 91, 37, 112, 73, 52, 58,
        37, 117, 45, 62, 37, 112, 73, 52, 58, 37, 117, 93, 34, 44, 32, 38, 115, 107, 101, 121, 46,
        108, 111, 99, 97, 108, 46, 105, 112, 52, 44, 32, 115, 107, 101, 121, 46, 108, 111, 99, 97,
        108, 46, 112, 111, 114, 116, 44, 32, 38, 115, 107, 101, 121, 46, 114, 101, 109, 111, 116,
        101, 46, 105, 112, 52, 44, 32, 115, 107, 101, 121, 46, 114, 101, 109, 111, 116, 101, 46,
        112, 111, 114, 116, 41, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 98, 112,
        102, 95, 112, 114, 105, 110, 116, 107, 40, 34, 65, 100, 100, 32, 115, 111, 99, 107, 101,
        116, 32, 91, 37, 112, 73, 52, 58, 37, 117, 45, 62, 37, 112, 73, 52, 58, 37, 117, 93, 34,
        44, 32, 38, 115, 107, 101, 121, 46, 108, 111, 99, 97, 108, 46, 105, 112, 52, 44, 32, 115,
        107, 101, 121, 46, 108, 111, 99, 97, 108, 46, 112, 111, 114, 116, 44, 32, 38, 115, 107,
        101, 121, 46, 114, 101, 109, 111, 116, 101, 46, 105, 112, 52, 44, 32, 115, 107, 101, 121,
        46, 114, 101, 109, 111, 116, 101, 46, 112, 111, 114, 116, 41, 59, 0, 32, 32, 32, 32, 114,
        101, 116, 117, 114, 110, 32, 110, 117, 109, 95, 117, 112, 103, 114, 97, 100, 101, 100, 95,
        99, 111, 110, 110, 115, 59, 0, 48, 58, 57, 0, 48, 58, 52, 0, 48, 58, 56, 0, 48, 58, 51, 0,
        48, 58, 55, 0, 48, 58, 48, 58, 48, 0, 48, 58, 48, 0, 108, 105, 99, 101, 110, 115, 101, 0,
        46, 98, 115, 115, 0, 46, 114, 111, 100, 97, 116, 97, 0, 46, 109, 97, 112, 115, 0, 46, 107,
        115, 121, 109, 115, 0, 46, 116, 101, 120, 116, 0, 115, 107, 95, 109, 115, 103, 0, 115, 111,
        99, 107, 111, 112, 115, 0, 115, 121, 115, 99, 97, 108, 108, 0, 0, 0, 0, 159, 235, 1, 0, 32,
        0, 0, 0, 0, 0, 0, 0, 84, 0, 0, 0, 84, 0, 0, 0, 36, 7, 0, 0, 120, 7, 0, 0, 12, 1, 0, 0, 8,
        0, 0, 0, 180, 15, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 43, 0, 0, 0, 136, 0, 0, 0, 45, 0, 0, 0,
        240, 0, 0, 0, 46, 0, 0, 0, 186, 15, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 47, 0, 0, 0, 193, 15, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 70, 0, 0, 0, 201, 15, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 72, 0, 0, 0,
        16, 0, 0, 0, 180, 15, 0, 0, 23, 0, 0, 0, 0, 0, 0, 0, 144, 4, 0, 0, 202, 4, 0, 0, 0, 200, 0,
        0, 40, 0, 0, 0, 144, 4, 0, 0, 29, 5, 0, 0, 9, 204, 0, 0, 48, 0, 0, 0, 144, 4, 0, 0, 47, 5,
        0, 0, 2, 212, 0, 0, 56, 0, 0, 0, 144, 4, 0, 0, 61, 5, 0, 0, 2, 216, 0, 0, 64, 0, 0, 0, 144,
        4, 0, 0, 75, 5, 0, 0, 2, 220, 0, 0, 72, 0, 0, 0, 144, 4, 0, 0, 89, 5, 0, 0, 2, 224, 0, 0,
        80, 0, 0, 0, 144, 4, 0, 0, 103, 5, 0, 0, 20, 232, 0, 0, 88, 0, 0, 0, 144, 4, 0, 0, 103, 5,
        0, 0, 2, 232, 0, 0, 120, 0, 0, 0, 144, 4, 0, 0, 145, 5, 0, 0, 2, 240, 0, 0, 136, 0, 0, 0,
        144, 4, 0, 0, 158, 5, 0, 0, 0, 252, 0, 0, 160, 0, 0, 0, 144, 4, 0, 0, 207, 5, 0, 0, 9, 0,
        1, 0, 168, 0, 0, 0, 144, 4, 0, 0, 47, 5, 0, 0, 2, 8, 1, 0, 176, 0, 0, 0, 144, 4, 0, 0, 89,
        5, 0, 0, 2, 12, 1, 0, 184, 0, 0, 0, 144, 4, 0, 0, 103, 5, 0, 0, 20, 20, 1, 0, 192, 0, 0, 0,
        144, 4, 0, 0, 103, 5, 0, 0, 2, 20, 1, 0, 224, 0, 0, 0, 144, 4, 0, 0, 145, 5, 0, 0, 2, 28,
        1, 0, 240, 0, 0, 0, 144, 4, 0, 0, 225, 5, 0, 0, 0, 40, 1, 0, 8, 1, 0, 0, 144, 4, 0, 0, 29,
        5, 0, 0, 9, 44, 1, 0, 16, 1, 0, 0, 144, 4, 0, 0, 47, 5, 0, 0, 2, 52, 1, 0, 24, 1, 0, 0,
        144, 4, 0, 0, 89, 5, 0, 0, 2, 56, 1, 0, 32, 1, 0, 0, 144, 4, 0, 0, 103, 5, 0, 0, 20, 64, 1,
        0, 40, 1, 0, 0, 144, 4, 0, 0, 103, 5, 0, 0, 2, 64, 1, 0, 72, 1, 0, 0, 144, 4, 0, 0, 145, 5,
        0, 0, 2, 72, 1, 0, 186, 15, 0, 0, 54, 0, 0, 0, 0, 0, 0, 0, 144, 4, 0, 0, 18, 6, 0, 0, 0,
        88, 1, 0, 8, 0, 0, 0, 144, 4, 0, 0, 59, 6, 0, 0, 25, 104, 1, 0, 16, 0, 0, 0, 144, 4, 0, 0,
        94, 6, 0, 0, 18, 100, 1, 0, 32, 0, 0, 0, 144, 4, 0, 0, 113, 6, 0, 0, 28, 96, 1, 0, 48, 0,
        0, 0, 144, 4, 0, 0, 142, 6, 0, 0, 26, 108, 1, 0, 56, 0, 0, 0, 144, 4, 0, 0, 94, 6, 0, 0,
        18, 100, 1, 0, 64, 0, 0, 0, 144, 4, 0, 0, 178, 6, 0, 0, 25, 120, 1, 0, 72, 0, 0, 0, 144, 4,
        0, 0, 214, 6, 0, 0, 19, 116, 1, 0, 80, 0, 0, 0, 144, 4, 0, 0, 234, 6, 0, 0, 21, 124, 1, 0,
        96, 0, 0, 0, 144, 4, 0, 0, 214, 6, 0, 0, 19, 116, 1, 0, 104, 0, 0, 0, 144, 4, 0, 0, 26, 7,
        0, 0, 46, 140, 1, 0, 128, 0, 0, 0, 144, 4, 0, 0, 26, 7, 0, 0, 50, 140, 1, 0, 136, 0, 0, 0,
        144, 4, 0, 0, 26, 7, 0, 0, 73, 140, 1, 0, 168, 0, 0, 0, 144, 4, 0, 0, 26, 7, 0, 0, 70, 140,
        1, 0, 184, 0, 0, 0, 144, 4, 0, 0, 105, 7, 0, 0, 5, 144, 1, 0, 240, 0, 0, 0, 144, 4, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 248, 0, 0, 0, 144, 4, 0, 0, 105, 7, 0, 0, 5, 144, 1, 0, 8, 1, 0, 0,
        144, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 1, 0, 0, 144, 4, 0, 0, 105, 7, 0, 0, 5, 144, 1,
        0, 56, 1, 0, 0, 144, 4, 0, 0, 24, 8, 0, 0, 19, 152, 1, 0, 88, 1, 0, 0, 144, 4, 0, 0, 96, 8,
        0, 0, 9, 156, 1, 0, 96, 1, 0, 0, 144, 4, 0, 0, 113, 8, 0, 0, 24, 160, 1, 0, 128, 1, 0, 0,
        144, 4, 0, 0, 151, 8, 0, 0, 13, 164, 1, 0, 136, 1, 0, 0, 144, 4, 0, 0, 179, 8, 0, 0, 13,
        168, 1, 0, 192, 1, 0, 0, 144, 4, 0, 0, 255, 8, 0, 0, 13, 188, 1, 0, 208, 1, 0, 0, 144, 4,
        0, 0, 27, 9, 0, 0, 17, 192, 1, 0, 224, 1, 0, 0, 144, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240,
        1, 0, 0, 144, 4, 0, 0, 50, 9, 0, 0, 13, 196, 1, 0, 16, 2, 0, 0, 144, 4, 0, 0, 50, 9, 0, 0,
        13, 196, 1, 0, 56, 2, 0, 0, 144, 4, 0, 0, 50, 9, 0, 0, 13, 196, 1, 0, 72, 2, 0, 0, 144, 4,
        0, 0, 50, 9, 0, 0, 13, 196, 1, 0, 96, 2, 0, 0, 144, 4, 0, 0, 82, 9, 0, 0, 32, 200, 1, 0,
        112, 2, 0, 0, 144, 4, 0, 0, 126, 9, 0, 0, 21, 204, 1, 0, 128, 2, 0, 0, 144, 4, 0, 0, 82, 9,
        0, 0, 32, 200, 1, 0, 136, 2, 0, 0, 144, 4, 0, 0, 126, 9, 0, 0, 21, 204, 1, 0, 168, 2, 0, 0,
        144, 4, 0, 0, 126, 9, 0, 0, 21, 204, 1, 0, 176, 2, 0, 0, 144, 4, 0, 0, 182, 9, 0, 0, 35,
        208, 1, 0, 184, 2, 0, 0, 144, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 200, 2, 0, 0, 144, 4, 0, 0,
        221, 9, 0, 0, 48, 224, 1, 0, 216, 2, 0, 0, 144, 4, 0, 0, 27, 10, 0, 0, 26, 220, 1, 0, 88,
        3, 0, 0, 144, 4, 0, 0, 221, 9, 0, 0, 57, 224, 1, 0, 104, 3, 0, 0, 144, 4, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 112, 3, 0, 0, 144, 4, 0, 0, 221, 9, 0, 0, 21, 224, 1, 0, 136, 3, 0, 0, 144, 4,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 144, 3, 0, 0, 144, 4, 0, 0, 68, 10, 0, 0, 21, 228, 1, 0, 200,
        3, 0, 0, 144, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 208, 3, 0, 0, 144, 4, 0, 0, 137, 10, 0, 0,
        21, 240, 1, 0, 240, 3, 0, 0, 144, 4, 0, 0, 50, 9, 0, 0, 13, 196, 1, 0, 16, 4, 0, 0, 144, 4,
        0, 0, 192, 10, 0, 0, 24, 8, 2, 0, 40, 4, 0, 0, 144, 4, 0, 0, 230, 10, 0, 0, 17, 36, 2, 0,
        56, 4, 0, 0, 144, 4, 0, 0, 192, 10, 0, 0, 24, 8, 2, 0, 80, 4, 0, 0, 144, 4, 0, 0, 0, 11, 0,
        0, 13, 40, 2, 0, 112, 4, 0, 0, 144, 4, 0, 0, 73, 11, 0, 0, 32, 44, 2, 0, 152, 4, 0, 0, 144,
        4, 0, 0, 110, 11, 0, 0, 1, 64, 2, 0, 193, 15, 0, 0, 33, 0, 0, 0, 0, 0, 0, 0, 144, 4, 0, 0,
        112, 11, 0, 0, 0, 76, 2, 0, 8, 0, 0, 0, 144, 4, 0, 0, 160, 11, 0, 0, 14, 80, 2, 0, 16, 0,
        0, 0, 144, 4, 0, 0, 160, 11, 0, 0, 56, 80, 2, 0, 24, 0, 0, 0, 144, 4, 0, 0, 160, 11, 0, 0,
        64, 80, 2, 0, 32, 0, 0, 0, 144, 4, 0, 0, 160, 11, 0, 0, 9, 80, 2, 0, 40, 0, 0, 0, 144, 4,
        0, 0, 11, 12, 0, 0, 9, 88, 2, 0, 64, 0, 0, 0, 144, 4, 0, 0, 54, 12, 0, 0, 29, 104, 2, 0,
        72, 0, 0, 0, 144, 4, 0, 0, 93, 12, 0, 0, 22, 100, 2, 0, 80, 0, 0, 0, 144, 4, 0, 0, 116, 12,
        0, 0, 30, 108, 2, 0, 88, 0, 0, 0, 144, 4, 0, 0, 93, 12, 0, 0, 22, 100, 2, 0, 96, 0, 0, 0,
        144, 4, 0, 0, 156, 12, 0, 0, 29, 120, 2, 0, 104, 0, 0, 0, 144, 4, 0, 0, 196, 12, 0, 0, 23,
        116, 2, 0, 112, 0, 0, 0, 144, 4, 0, 0, 220, 12, 0, 0, 25, 124, 2, 0, 128, 0, 0, 0, 144, 4,
        0, 0, 196, 12, 0, 0, 23, 116, 2, 0, 136, 0, 0, 0, 144, 4, 0, 0, 16, 13, 0, 0, 9, 140, 2, 0,
        160, 0, 0, 0, 144, 4, 0, 0, 11, 12, 0, 0, 9, 88, 2, 0, 168, 0, 0, 0, 144, 4, 0, 0, 16, 13,
        0, 0, 9, 140, 2, 0, 176, 0, 0, 0, 144, 4, 0, 0, 147, 13, 0, 0, 32, 96, 2, 0, 192, 0, 0, 0,
        144, 4, 0, 0, 16, 13, 0, 0, 9, 140, 2, 0, 208, 0, 0, 0, 144, 4, 0, 0, 11, 12, 0, 0, 9, 88,
        2, 0, 216, 0, 0, 0, 144, 4, 0, 0, 16, 13, 0, 0, 9, 140, 2, 0, 0, 1, 0, 0, 144, 4, 0, 0,
        180, 13, 0, 0, 32, 148, 2, 0, 24, 1, 0, 0, 144, 4, 0, 0, 180, 13, 0, 0, 25, 148, 2, 0, 32,
        1, 0, 0, 144, 4, 0, 0, 180, 13, 0, 0, 36, 148, 2, 0, 40, 1, 0, 0, 144, 4, 0, 0, 180, 13, 0,
        0, 59, 148, 2, 0, 64, 1, 0, 0, 144, 4, 0, 0, 180, 13, 0, 0, 51, 148, 2, 0, 72, 1, 0, 0,
        144, 4, 0, 0, 180, 13, 0, 0, 13, 148, 2, 0, 88, 1, 0, 0, 144, 4, 0, 0, 246, 13, 0, 0, 17,
        152, 2, 0, 136, 1, 0, 0, 144, 4, 0, 0, 246, 13, 0, 0, 17, 152, 2, 0, 152, 1, 0, 0, 144, 4,
        0, 0, 66, 14, 0, 0, 17, 156, 2, 0, 8, 2, 0, 0, 144, 4, 0, 0, 214, 14, 0, 0, 13, 172, 2, 0,
        104, 2, 0, 0, 144, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 120, 2, 0, 0, 144, 4, 0, 0, 110, 11, 0,
        0, 1, 192, 2, 0, 201, 15, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 144, 4, 0, 0, 85, 15, 0, 0, 12,
        208, 2, 0, 16, 0, 0, 0, 144, 4, 0, 0, 85, 15, 0, 0, 5, 208, 2, 0, 16, 0, 0, 0, 180, 15, 0,
        0, 3, 0, 0, 0, 88, 0, 0, 0, 29, 0, 0, 0, 116, 15, 0, 0, 0, 0, 0, 0, 192, 0, 0, 0, 29, 0, 0,
        0, 116, 15, 0, 0, 0, 0, 0, 0, 40, 1, 0, 0, 29, 0, 0, 0, 116, 15, 0, 0, 0, 0, 0, 0, 186, 15,
        0, 0, 6, 0, 0, 0, 8, 0, 0, 0, 29, 0, 0, 0, 120, 15, 0, 0, 0, 0, 0, 0, 48, 0, 0, 0, 29, 0,
        0, 0, 124, 15, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 29, 0, 0, 0, 128, 15, 0, 0, 0, 0, 0, 0, 80,
        0, 0, 0, 29, 0, 0, 0, 132, 15, 0, 0, 0, 0, 0, 0, 184, 0, 0, 0, 29, 0, 0, 0, 116, 15, 0, 0,
        0, 0, 0, 0, 136, 1, 0, 0, 29, 0, 0, 0, 136, 15, 0, 0, 0, 0, 0, 0, 193, 15, 0, 0, 6, 0, 0,
        0, 8, 0, 0, 0, 60, 0, 0, 0, 142, 15, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 60, 0, 0, 0, 142, 15,
        0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 60, 0, 0, 0, 120, 15, 0, 0, 0, 0, 0, 0, 80, 0, 0, 0, 60, 0,
        0, 0, 124, 15, 0, 0, 0, 0, 0, 0, 96, 0, 0, 0, 60, 0, 0, 0, 128, 15, 0, 0, 0, 0, 0, 0, 112,
        0, 0, 0, 60, 0, 0, 0, 132, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0,
        0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 44, 2, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9,
        0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 112, 2, 0, 0, 0, 0, 0,
        0, 240, 3, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0,
        0, 0, 0, 0, 17, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 96, 6,
        0, 0, 0, 0, 0, 0, 88, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 23, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 184, 7, 0, 0, 0, 0, 0, 0, 168, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 30, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 96, 12, 0, 0, 0, 0, 0, 0, 136, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 38, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 232, 14, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 46, 0, 0, 0, 1, 0, 0,
        0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 15, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 54, 0, 0,
        0, 8, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 15, 0, 0, 0, 0, 0, 0, 4,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 59, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 15, 0, 0,
        0, 0, 0, 0, 221, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 67, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        240, 15, 0, 0, 0, 0, 0, 0, 96, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 251, 1, 0, 0, 9, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 80, 16, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0,
        8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 6, 2, 0, 0, 9, 0, 0, 0, 64, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 80, 17, 0, 0, 0, 0, 0, 0, 96, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0,
        0, 5, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 18, 2, 0, 0, 9, 0, 0, 0,
        64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 176, 17, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0,
        0, 0, 0, 2, 0, 0, 0, 6, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 30, 2, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 17, 0, 0, 0, 0, 0, 0,
        141, 26, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 35, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 80, 44,
        0, 0, 0, 0, 0, 0, 164, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
    ];
}
