[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
as-bytes = "0.2.0"
axum = { version = "0.8.9", features = ["http2"] }
beeline = { path = "../beeline", features = ["h1", "h2"] }
bytes = "1.11.1"
libbpf-rs = "0.27.0"
libc = "0.2.186"
tokio = { version = "1.52", features = ["full"] }
bpf-tracing = "0.0.5"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[build-dependencies]
libbpf-cargo = "0.26.2"
beeline-include = { path = "../beeline-include" }
