[package]
name = "beeline"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
as-bytes = "0.2.0"
bytes = "1.10.1"
env_logger = "0.11.8"
httlib-huffman = "0.3.4"
libbpf-rs = "0.25.0"
libc = "0.2.178"
log = "0.4.27"

[build-dependencies]
libbpf-cargo = "0.25.0"

[dev-dependencies]
reqwest = "0.12.20"
tokio = { version = "1.45.1", features = ["full"] }
utils = { path = "../utils" }
