[package]
name = "beeline"
version = "0.1.0"
edition = "2024"

[features]
default = ["h1", "h2"]
h1 = []
h2 = []

[dependencies]
anyhow = "1.0.102"
as-bytes = "0.2.0"
bpf-tracing = "0.0.5"
bytes = "1.11.1"
httlib-huffman = "0.3.4"
libbpf-rs = "0.26.2"
libc = "0.2.186"
tracing = "0.1.44"

[build-dependencies]
libbpf-cargo = "0.26.2"
beeline-include = { path = "../beeline-include" }

[dev-dependencies]
reqwest = "0.13.3"
tokio = { version = "1.52", features = ["full"] }
utils = { path = "../utils" }
